// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/enquiry-booking/BookingSuccess.tsx": () => import("../components/mockups/enquiry-booking/BookingSuccess.tsx"),
  "./components/mockups/enquiry-booking/Current.tsx": () => import("../components/mockups/enquiry-booking/Current.tsx")
};
